# Generated by Django 6.0.2 on 2026-05-13 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('superadmin', 'Super Administrador'), ('coordinador_departamental', 'Coordinador Departamental'), ('coordinador_provincial', 'Coordinador Provincial'), ('visor', 'Visor (Solo Lectura)'), ('personero', 'Personero')], default='visor', max_length=30, verbose_name='Rol')),
                ('departamento', models.CharField(blank=True, choices=[('AMA', 'Amazonas'), ('ANC', 'Áncash'), ('APU', 'Apurímac'), ('ARE', 'Arequipa'), ('AYA', 'Ayacucho'), ('CAJ', 'Cajamarca'), ('CAL', 'Callao'), ('CUS', 'Cusco'), ('HUV', 'Huancavelica'), ('HUA', 'Huánuco'), ('ICA', 'Ica'), ('JUN', 'Junín'), ('LAL', 'La Libertad'), ('LAM', 'Lambayeque'), ('LIM', 'Lima'), ('LOR', 'Loreto'), ('MDM', 'Madre de Dios'), ('MOQ', 'Moquegua'), ('PAS', 'Pasco'), ('PIU', 'Piura'), ('PUN', 'Puno'), ('SAM', 'San Martín'), ('TAC', 'Tacna'), ('TUM', 'Tumbes'), ('UCA', 'Ucayali')], help_text='Solo para coordinadores departamentales', max_length=3, null=True, verbose_name='Departamento asignado')),
                ('provincia', models.CharField(blank=True, help_text='Solo para coordinadores provinciales', max_length=100, null=True, verbose_name='Provincia asignada')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Personero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido_paterno', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(max_length=100, verbose_name='Apellido Materno')),
                ('nombres', models.CharField(max_length=200, verbose_name='Nombres')),
                ('dni', models.CharField(max_length=8, unique=True, verbose_name='DNI')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('nro_celular', models.CharField(blank=True, max_length=20, verbose_name='Nro. Celular')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('departamento', models.CharField(blank=True, choices=[('AMA', 'Amazonas'), ('ANC', 'Áncash'), ('APU', 'Apurímac'), ('ARE', 'Arequipa'), ('AYA', 'Ayacucho'), ('CAJ', 'Cajamarca'), ('CAL', 'Callao'), ('CUS', 'Cusco'), ('HUV', 'Huancavelica'), ('HUA', 'Huánuco'), ('ICA', 'Ica'), ('JUN', 'Junín'), ('LAL', 'La Libertad'), ('LAM', 'Lambayeque'), ('LIM', 'Lima'), ('LOR', 'Loreto'), ('MDM', 'Madre de Dios'), ('MOQ', 'Moquegua'), ('PAS', 'Pasco'), ('PIU', 'Piura'), ('PUN', 'Puno'), ('SAM', 'San Martín'), ('TAC', 'Tacna'), ('TUM', 'Tumbes'), ('UCA', 'Ucayali')], max_length=3, verbose_name='Departamento')),
                ('provincia', models.CharField(blank=True, max_length=100, verbose_name='Provincia')),
                ('distrito', models.CharField(blank=True, max_length=100, verbose_name='Distrito')),
                ('colegio_electoral', models.CharField(blank=True, max_length=200, verbose_name='Colegio Electoral')),
                ('numero_mesa', models.CharField(blank=True, max_length=10, verbose_name='Nro. de Mesa')),
                ('cargo', models.CharField(choices=[('titular', 'Titular'), ('suplente', 'Suplente')], default='titular', max_length=10, verbose_name='Cargo')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('retirado', 'Retirado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('perfil_completado', models.BooleanField(default=False, verbose_name='Perfil Completado')),
                ('fecha_completado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Completado')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personero', to=settings.AUTH_USER_MODEL, verbose_name='Usuario del Sistema')),
            ],
            options={
                'verbose_name': 'Personero',
                'verbose_name_plural': 'Personeros',
                'ordering': ['apellido_paterno', 'apellido_materno'],
            },
        ),
    ]
