# Generated by Django 6.0.2 on 2026-05-14 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personeros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personero',
            name='colegio_electoral',
        ),
        migrations.CreateModel(
            name='CentroVotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(default='CALLAO', max_length=100, verbose_name='Región')),
                ('provincia', models.CharField(default='CALLAO', max_length=100, verbose_name='Provincia')),
                ('distrito', models.CharField(max_length=100, verbose_name='Distrito')),
                ('nombre', models.CharField(max_length=300, verbose_name='Centro de Votación')),
                ('direccion', models.CharField(blank=True, max_length=300, verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Centro de Votación',
                'verbose_name_plural': 'Centros de Votación',
                'ordering': ['distrito', 'nombre'],
                'unique_together': {('nombre', 'distrito')},
            },
        ),
        migrations.AddField(
            model_name='personero',
            name='centro_votacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personeros', to='personeros.centrovotacion', verbose_name='Centro de Votación'),
        ),
    ]
