# Generated by Django 6.0.2 on 2026-05-14 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personeros', '0002_centrovotacion_y_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_ubigeo', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Código UBIGEO')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id_ubigeo', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Código UBIGEO')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Distrito',
                'verbose_name_plural': 'Distritos',
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='centrovotacion',
            name='provincia',
        ),
        migrations.RemoveField(
            model_name='centrovotacion',
            name='region',
        ),
        migrations.RemoveField(
            model_name='personero',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='personero',
            name='provincia',
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personeros.departamento', verbose_name='Departamento asignado'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='distrito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personeros.distrito', verbose_name='Distrito asignado'),
        ),
        migrations.AlterField(
            model_name='centrovotacion',
            name='distrito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centros', to='personeros.distrito'),
        ),
        migrations.AlterField(
            model_name='personero',
            name='distrito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personeros.distrito', verbose_name='Distrito'),
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id_ubigeo', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Código UBIGEO')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provincias', to='personeros.departamento')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='distrito',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distritos', to='personeros.provincia'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personeros.provincia', verbose_name='Provincia asignada'),
        ),
    ]
