# Generated by Django 6.0.2 on 2026-05-14 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personeros', '0003_normalization_ubigeo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personero',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('retirado', 'Retirado')], default='confirmado', max_length=20, verbose_name='Estado'),
        ),
    ]
