# Generated by Django 6.0.2 on 2026-05-18 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personeros', '0004_alter_personero_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActaElectoral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_mesa', models.CharField(max_length=10, verbose_name='Número de Mesa')),
                ('votos_jp', models.PositiveIntegerField(default=0, verbose_name='Votos JP')),
                ('votos_k', models.PositiveIntegerField(default=0, verbose_name='Votos K')),
                ('votos_blanco', models.PositiveIntegerField(default=0, verbose_name='Votos Blanco')),
                ('votos_nulos', models.PositiveIntegerField(default=0, verbose_name='Votos Nulos')),
                ('votos_viciados', models.PositiveIntegerField(default=0, verbose_name='Votos Viciados')),
                ('foto_acta', models.ImageField(blank=True, null=True, upload_to='actas_fotos/', verbose_name='Foto de Acta')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('verificado', models.BooleanField(default=False, verbose_name='Verificado por Coordinador')),
                ('centro_votacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personeros.centrovotacion', verbose_name='Centro de Votación')),
                ('personero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acta', to='personeros.personero', verbose_name='Personero')),
            ],
            options={
                'verbose_name': 'Acta Electoral',
                'verbose_name_plural': 'Actas Electorales',
                'unique_together': {('centro_votacion', 'numero_mesa')},
            },
        ),
    ]
