# Generated by Django 6.0.2 on 2026-05-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personeros', '0005_actaelectoral'),
    ]

    operations = [
        migrations.AddField(
            model_name='centrovotacion',
            name='actas',
            field=models.IntegerField(default=0, verbose_name='Actas'),
        ),
    ]
