# Generated by Django 6.0.2 on 2026-05-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personeros', '0006_centrovotacion_actas'),
    ]

    operations = [
        migrations.AddField(
            model_name='centrovotacion',
            name='electores',
            field=models.IntegerField(default=0, verbose_name='Electores'),
        ),
    ]
