# Generated by Django 6.0.2 on 2026-05-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personeros', '0007_centrovotacion_electores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personero',
            name='cargo',
            field=models.CharField(choices=[('Coordinador1', 'Coordinador Zonal'), ('Coordinador2', 'Personero Centro de Votación'), ('Coordinador3', 'Personero Mesa de Sufragio')], default='Coordinador1', max_length=20, verbose_name='Cargo'),
        ),
    ]
