# Generated by Django 6.0.2 on 2026-05-28 19:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personeros', '0008_alter_personero_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='personero',
            name='token_uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, verbose_name='Token de Verificación QR'),
        ),
    ]
