# Generated by Django 6.0.2 on 2026-05-28 19:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personeros', '0009_personero_token_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personero',
            name='token_uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True, verbose_name='Token de Verificación QR'),
        ),
    ]
