# Generated by Django 6.0.2 on 2026-05-29 16:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personeros', '0010_alter_personero_token_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='personero',
            constraint=models.UniqueConstraint(condition=models.Q(('cargo', 'Coordinador2'), ('estado__in', ['pendiente', 'confirmado'])), fields=('centro_votacion', 'cargo'), name='unique_active_personero_centro_votacion'),
        ),
    ]
