# Generated by Django 6.0.2 on 2026-02-26 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brigadista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo_referencia', models.CharField(max_length=50, unique=True)),
                ('zona', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('texto_sabotaje', models.TextField()),
                ('pregunta_reflexion', models.TextField()),
                ('nombre_propuesta', models.CharField(max_length=200)),
                ('impacto_detalle', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Participacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_vecino', models.CharField(max_length=200)),
                ('whatsapp', models.CharField(max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('referido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plataforma.brigadista')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.tema')),
            ],
        ),
    ]
