# Generated by Django 6.0.2 on 2026-02-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='opcion_no',
            field=models.CharField(default='No sabía que pasaba eso', max_length=150),
        ),
        migrations.AddField(
            model_name='tema',
            name='opcion_si',
            field=models.CharField(default='SÍ, lo vivo a diario', max_length=150),
        ),
    ]
