# Generated by Django 6.0.2 on 2026-02-26 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_tema_opcion_no_tema_opcion_si'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='texto_contexto_no',
            field=models.TextField(blank=True, default='Aquí tienes más información sobre lo que está ocurriendo actualmente...', null=True),
        ),
    ]
