# Generated by Django 6.0.2 on 2026-02-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0003_tema_texto_contexto_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='participacion',
            name='dni',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
