# Generated by Django 6.0.2 on 2026-02-27 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0004_participacion_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participacion',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
