# Generated by Django 6.0.2 on 2026-02-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0005_alter_participacion_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='participacion',
            name='tema_libre',
            field=models.CharField(blank=True, help_text="Especificar tema si se seleccionó 'Otros'", max_length=255, null=True),
        ),
    ]
