# Generated by Django 6.0.2 on 2026-05-15 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0006_participacion_tema_libre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text='Ruta en la URL (ej. eduardo-herrera)', unique=True)),
                ('cargo', models.CharField(choices=[('diputado', 'Diputado'), ('senador_nacional', 'Senador Nacional'), ('senador_regional', 'Senador Regional'), ('parlamento_andino', 'Parlamento Andino')], default='diputado', max_length=50)),
                ('ubicacion', models.CharField(default='Callao', max_length=100)),
                ('foto_estatica', models.CharField(default='RetratoSinFondoCamisaBlancaConLogo.png', max_length=200)),
                ('whatsapp_url', models.URLField(blank=True, default='https://wa.me/51954124774', null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('tiktok_url', models.URLField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='participacion',
            name='candidato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plataforma.candidato'),
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_direccion', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ruta', models.CharField(default='/', max_length=255)),
                ('referido_por', models.CharField(blank=True, max_length=100, null=True)),
                ('candidato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plataforma.candidato')),
            ],
        ),
    ]
